language: go
os:
  - linux

env:
 - TAGS="-tags travis"

cache:
 directories:
   - $HOME/.cache/go-build
   - $HOME/gopath/pkg/mod

matrix:
 fast_finish: true
 allow_failures:
   - go: master
 include:
   - go: 1.9.x
     env:
       - TAGS="-tags travis"
   - go: 1.10.x
     env:
       - TAGS="-tags travis"
   - go: 1.11.x
     env:
       - TAGS="-tags travis"
       - COVERAGE="-cover -race"
   - go: master
     env:
       - TAGS="-tags travis"
       - COVERAGE="-race"
       - GO111MODULE="on"

sudo: false

addons:
  apt:
    packages:
      - libhdf5-serial-dev

notifications:
  email:
    recipients:
      - binet@cern.ch
    on_success: always
    on_failure: always

script:
 - go get -d -t -v ./...
 - go install -v $TAGS ./...
 - go run ./ci/run-tests.go $TAGS $COVERAGE

after_success:
 - bash <(curl -s https://codecov.io/bash)
